---
settings:
  name: Software updates
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de actualizaciones de software
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: ontap
  - section: support
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
